# Generated by Django 4.0.4 on 2022-08-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup_user',
            name='access',
        ),
        migrations.AddField(
            model_name='setup_user',
            name='access1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='setup_user',
            name='access2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='setup_user',
            name='access3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='setup_user',
            name='access4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='setup_user',
            name='userid',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
