# Generated by Django 4.0.4 on 2022-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sejarahAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('staff', models.CharField(max_length=10)),
                ('programme', models.CharField(max_length=10)),
                ('element', models.CharField(max_length=10)),
                ('indicator', models.CharField(max_length=10)),
                ('subIndicator', models.CharField(max_length=10)),
                ('outcome', models.CharField(max_length=10)),
                ('remark', models.CharField(max_length=10)),
            ],
        ),
    ]
