# Generated by Django 4.0.4 on 2022-06-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setupUser', '0002_sejarahaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='pp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('p', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='elemen',
            old_name='type',
            new_name='pengauditan',
        ),
    ]
