# Generated by Django 4.0.4 on 2022-07-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setupUser', '0003_pengauditan_rename_type_elemen_pengauditan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sejarahaudit',
            old_name='element',
            new_name='pp',
        ),
    ]
