# Generated by Django 4.0.4 on 2022-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maklumbalas_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('pengauditan', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('subIndicator', models.CharField(max_length=100)),
                ('auditor', models.CharField(max_length=100)),
                ('criteria', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('catatan', models.CharField(max_length=100)),
                ('att', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pelaksanaan_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('pengauditan', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('subIndicator', models.CharField(max_length=100)),
                ('auditor', models.CharField(max_length=100)),
                ('criteria', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('f', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pemerhatian_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('pengauditan', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('subIndicator', models.CharField(max_length=100)),
                ('auditor', models.CharField(max_length=100)),
                ('criteria', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('att', models.CharField(max_length=100)),
                ('catatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='perancangan_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('pengauditan', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('subIndicator', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('auditor', models.CharField(max_length=100)),
                ('f', models.CharField(max_length=100)),
                ('t', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='risk_assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('risk', models.CharField(max_length=100)),
                ('pengauditan', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('subIndicator', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
                ('Kebarangkalian', models.CharField(max_length=100)),
                ('Impak', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
    ]
