# Generated by Django 4.0.4 on 2022-08-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditUser', '0002_remove_pelaksanaan_audit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='perancangan_audit',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
