# Generated by Django 4.0.4 on 2022-08-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditUser', '0003_perancangan_audit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maklumbalas_audit',
            name='elemen',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelaksanaan_audit',
            name='elemen',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pemerhatian_audit',
            name='elemen',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perancangan_audit',
            name='elemen',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
